apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: An externally developed shell
  tags:
    - simple
    - shell
  annotations:
    github.com/project-slug: eMarv/test
spec:
  type: shell
  lifecycle: dev
  owner: external
